name: development deployment

concurrency: 
  group: development
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - master
    
jobs:
  deployment:
    name: Deploy de la mort sur dev
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Deploying on development
        run: echo "Deploying..."
