name: production deployment

concurrency: 
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - master
    
jobs:
  deployment:
    name: Deploy de la mort
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Deploying on production
        run: echo "Deploying..."
