name: verify Branch is Up to Date

on:
  push:
    branches:
      - test

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Fetch Latest Changes
      run: |
        git fetch origin
        git branch -u origin/master test

    - name: Verify Branch is Up to Date
      run: |
        UPSTREAM=${1:-'@{u}'}
        LOCAL=$(git rev-parse @)
        REMOTE=$(git rev-parse "$UPSTREAM")
        BASE=$(git merge-base @ "$UPSTREAM")

        if [ $LOCAL = $REMOTE ]; then
          echo "Branch is up to date"
        elif [ $LOCAL = $BASE ]; then
          echo "Branch is behind"
          exit 1
        else
          echo "Branch has diverged"
          exit 1
        fi
The above example checks out your branch mybranch, fetches the latest changes from the remote repository, and compares your branch with the main branch. If the branch is up to date, it will print "Branch is up to date". If the branch is behind the main branch, it will print "Branch is behind" and exit with status code 1. If the branch has diverged, it will print "Branch has diverged" and exit with status code 1.




