name: Verify Branch is Up to Date

on:
  push:
    branches:
      - toto

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Fetch Latest Changes
      run: |
        git fetch origin toto
        git checkout toto

    - name: Verify Branch is Up to Date
      run: |
        DIFF=$(git rev-list --left-only --count origin/master...@)

        if [ $DIFF -eq 0 ]; then
          echo "Branch is up to date"
        else
          echo "Branch is behind"
          exit 1
        fi
