name: verify Branch is Up to Date

on:
  push:
    branches:
      - test

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Fetch Latest Changes
      run: |
        git fetch origin
        git branch -u origin/master test

    - name: Verify Branch is Up to Date
      run: |
        UPSTREAM=${1:-'@{u}'}
        LOCAL=$(git rev-parse @)
        REMOTE=$(git rev-parse "$UPSTREAM")
        BASE=$(git merge-base @ "$UPSTREAM")

        if [ $LOCAL = $REMOTE ]; then
          echo "Branch is up to date"
        elif [ $LOCAL = $BASE ]; then
          echo "Branch is behind"
          exit 1
        else
          echo "Branch has diverged"
          exit 1
        fi




